# ci for product catalog service

name: product-catalog-service-ci
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up go 1.22
              uses: actions/setup-go@v4
              with:
                go-version: '1.22'

            - name: Build
              run: |
                cd src/product-catalog-service
                go mod download
                go build -v ./...

            - name: Run tests
              run: |
                cd src/product-catalog-service
                go test ./...

    code-quality:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install golangci-lint
              run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

            - name: Run linters
              run: |
                export PATH=$PATH:$(go env GOPATH)/bin
                golangci-lint run ./src/product-catalog-service/...

    docker:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./src/product-catalog-service/Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog-service:${{ github.run_id }}

    update-k8s:
        runs-on: ubuntu-latest
        needs: docker
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Update k8s deployment file
              run: |
                sed -i 's|image: .*|image: '"${{ secrets.DOCKER_USERNAME }}"'/product-catalog-service:'"${{ github.run_id }}"'|g' ./k8s/product-catalog-service-deployment.yaml
                cat ./k8s/product-catalog-service-deployment.yaml

            - name: Commit and push changes
              run: |
                git config user.name "GitHub Action"
                git config user.email "action@github.com"
                git add ./k8s/product-catalog-service-deployment.yaml
                git commit -m "Update k8s deployment image to ${{ github.sha }}"
                git push